version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Diagnostics
          command: |
            echo "hello from circleci"
            python --version
            pwd
            ls -la
