version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements-dev.txt
      - run:
          name: Run tests
          command: |
            mkdir -p test-results
            pytest

workflows:
  build-test:
    jobs:
      - build-and-test
